local kwds = {
    ["externluaf"] = "ExternLuaFunction",
    ["copy"] = "Copy",
            ["add"] = "Add",
            ["sub"] = "Sub",
            ["mul"] = "Mul",
            ["div"] = "Div",
            ["mod"] = "Mod",
            
            ["neg"] = "Negation",

            ["eq"] = "Equals",
            ["ne"] = "NotEquals",
            ["gt"] = "Greater",
            ["lt"] = "Less",
            ["ge"] = "GreaterEqual",
            ["le"] = "LessEqual",
            
            ["or"] = "Or",
            ["and"] = "And",
            ["not"] = "Not",
            ["compare"] = "Compare",
            ["pushframe"] = "PushFrame",
            ["popframe"] = "PopFrame",
            ["store"] = "Store",
            ["load"] = "Load",
            ["call"] = "Call",
            ["ret"] = "Return",
            ["return"] = "Return",
            ["luacall"] = "LuaCall",
            ["loadservice"] = "LoadService",
            ["loadsvc"] = "LoadService",
            ["invokeservice"] = "InvokeService",
            ["invokesvc"] = "InvokeService",
            ["exit"] = "Exit",
            ["jump_eq"] = "JumpIfEq",
            ["jump_lt"] = "JumpIfLt",
            ["jump_le"] = "JumpIfLe",
            ["jump_gt"] = "JumpIfGt",
            ["jump_ge"] = "JumpIfGe",
            ["jump_neq"] = "JumpIfNeq",
            ["jump_nlt"] = "JumpIfNlt",
            ["jump_nle"] = "JumpIfNle",
            ["jump_ngt"] = "JumpIfNgt",
            ["jump_nge"] = "JumpIfNge",
            ["jump"] = "Jump",
            ["isetptr"] = "ISetPtr",
            ["fsetptr"] = "FSetPtr",
            ["ssetptr"] = "SSetPtr",
            ["igetptr"] = "IGetPtr",
            ["fgetptr"] = "FGetPtr",
            ["sgetptr"] = "SGetPtr",
}

return kwds